package localscheduler

import (
	"context"

	apiv1 "github.com/goobers/goobers/api/v1alpha1"
	"github.com/goobers/goobers/internal/journal"
)

// Starter is the "start a run" seam the scheduler dispatches through once a
// tick is due and run conditions admit it (issue #17, coordinated on
// #mission-runner-core). One Starter per workflow: #17's *runner.Runner is
// bound to a single compiled machine at construction, so the scheduler holds a
// map of workflow name -> Starter, not one Starter for everything.
//
// StartRequest/StartResult mirror runner.StartInput/Result field-for-field
// where they overlap (RunID, GooberDigest, Gaggle, Trigger, RepoRef, Item), so
// adapting a *runner.Runner into a Starter is a straight field copy. They're declared
// locally rather than imported from internal/runner so this package builds and
// tests independently of #17's landing order — see the Starter seam thread on
// #mission-runner-core for the coordination.
type Starter interface {
	Start(ctx context.Context, req StartRequest) (StartResult, error)
}

// DispatchRegistration lets a starter register its work before the scheduler
// launches the dispatch goroutine. This keeps an external shutdown wait from
// racing a starter's first instruction.
type DispatchRegistration interface {
	RegisterDispatch() func()
}

func registerDispatch(starter Starter) func() {
	if registered, ok := starter.(DispatchRegistration); ok {
		return registered.RegisterDispatch()
	}
	return func() {}
}

// StartRequest is what triggers one run. RunID is generated by the scheduler
// (telemetry.NewRunID) before dispatch, since the scheduler needs it as the
// claim-ledger key before the run exists — the runner creates the journal
// using this exact id rather than minting its own, so claim-ledger identity and
// run identity are the same value throughout.
type StartRequest struct {
	RunID        string
	GooberDigest string
	Gaggle       string
	Trigger      journal.Trigger
	RepoRef      apiv1.RepoRef
	// Item is the originating backlog item for a claimed unit of work. Nil for
	// a schedule/signal-triggered producer run.
	Item *apiv1.BacklogItem
}

type gooberDigestStarter struct {
	digest string
	next   Starter
}

func (s gooberDigestStarter) Start(ctx context.Context, req StartRequest) (StartResult, error) {
	req.GooberDigest = s.digest
	return s.next.Start(ctx, req)
}

func (s gooberDigestStarter) RegisterDispatch() func() {
	return registerDispatch(s.next)
}

// StartResult is a run's outcome as of the moment Start returns — which may be
// a human-gate pause, not necessarily a terminal state (§5).
type StartResult struct {
	Phase      journal.RunPhase
	FinalState string
	NoWork     bool
	// FailureStage/FailureCode/FailureMessage mirror runner.Result's same-named
	// fields (issue #710) — populated only for Phase == PhaseFailed, empty
	// otherwise. The scheduler's dispatch echo (scheduler.go) threads these
	// onto the instance-journal run.finished event so a business failure's
	// actual cause is visible one level up, not just inside the run's own
	// journal.
	FailureStage   string
	FailureCode    string
	FailureMessage string
}
